---
 - name: Copiar Escriptoris entre IPs
   hosts: all
   become: yes
   vars_prompt:

      - name: ip_origen
        prompt: IP Origen
        private: no
        when: ip_origen is not defined

      - name: ip_desti
        prompt: IP Destí
        private: no
        when: ip_desti is not defined
      
   tasks:
      - name: Print a message
        ansible.builtin.debug:
          msg: 'Iporigen {{ ip_origen }} ipdesti {{ ip_desti }}'

#scp -P 20592 -r examen@158.109.202.128:/home/examen /home/pere/Documents/.
#scp -P 20592 -r /home/pere/Documents/examen_128.zip examen@158.109.202.130:/home/examen/Escritorio/.
      - name: Copiar de Origen a local
        ansible.builtin.shell: sshpass -f "/home/test/Documents/pass.txt" scp -P 20592 -r ansible@{{ ip_origen }}:/home/test /home/test/Documents/.
#      - name: change timezone using timedatactl
#        ansible.builtin.shell: timedatectl set-timezone Europe/Andorra
#        
#      - name: download timesyncd.conf from github
#        get_url:
#          url: https://raw.githubusercontent.com/git366/yml/main/timesyncd.conf
#          dest: /home/ansible/timesyncd.conf
#          mode: 0440
#      # Copy a new "ntp.conf file into place, backing up the original if it differs from the copied version
#      - name: copy the downloaded file to systemd
#        copy:
#          src: /home/ansible/timesyncd.conf
#          dest: /etc/systemd/timesyncd.conf
#          remote_src: yes #els dos directoris son remots
#          owner: root
#          group: root
#          mode: 0644
#          backup: yes
        
#      - name: restart systemd service to reload de .conf
#        ansible.builtin.shell: systemctl restart systemd-timesyncd
#      - name: Update hour by NTP
#        ansible.builtin.shell: systemctl status systemd-timesyncd
