---
- hosts: all
  gather_facts: no
  tasks:
   - name: "Shutdown" 
     command: "shutdown -h now"
     async: 0
     poll: 0
     ignore_errors: true
     when: operacion == "shutdown"
 
   - name: "Reboot" 
     command: "shutdown -r now"
     async: 0
     poll: 0
     ignore_errors: true
     when: operacion == "reboot"
