---
 - name: NTP config
   hosts: all
   become: yes
   tasks:
#      - name: change timezone
#        ansible.builtin.shell: echo Europe/Andorra > /etc/timezone
      - name: change timezone2
        ansible.builtin.shell: timedatectl set-timezone Europe/Andorra
        
      - name: download timesyncd.conf
        get_url:
          url: https://raw.githubusercontent.com/git366/yml/main/timesyncd.conf
          dest: /home/ansible/timesyncd.conf
          mode: 0440
      # Copy a new "ntp.conf file into place, backing up the original if it differs from the copied version
      - copy:
          src: /home/ansible/timesyncd.conf
          dest: /etc/systemd/timesyncd.conf
          remote_src: yes #els dos directoris son remots
          owner: root
          group: root
          mode: 0644
          backup: yes
        
      - name: restart service
        ansible.builtin.shell: systemctl restart systemd-timesyncd
      - name: Update hour by NTP
        ansible.builtin.shell: systemctl status systemd-timesyncd

